services:
  # Model servers
  vllm-embed:
    image: vllm/vllm-openai:latest
    container_name: vllm-embed
    network_mode: host
    ipc: host
    #ports:
    #  - "8091:8000" # VLLM API access
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
      - ${HOME}/gb10/vllm_cache/vllm_embed:/root/.cache/vllm
    command: >
      --model Qwen/Qwen3-Embedding-4B
      --runner pooling
      --port 8091
      --gpu-memory-utilization 0.25
      --compilation-config '{"cache_dir": "/root/.cache/vllm"}'
    restart: "no"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/health"]
      interval: 30s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  # Models: 
  vllm:
    profiles:
      - nvidia/Nemotron-Cascade-2-30B-A3B
    #image: nvcr.io/nvidia/vllm:26.01-py3
    image: vllm/vllm-openai:latest #v0.18.0-cu130
    #build:
    #  context: .
    #  dockerfile: vllm/Dockerfile
    container_name: vllm
    network_mode: host
    ipc: host
    #ports:
    #  - "8090:8000" # VLLM API access
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
      - ${HOME}/gb10/vllm_cache/vllm_nemotron_cascade-2:/root/.cache/vllm
    command: >
      --model nvidia/Nemotron-Cascade-2-30B-A3B
      --dtype bfloat16
      --tensor-parallel-size 1
      --port 8090
      --max-model-len 262144
      --gpu-memory-utilization 0.65
      --reasoning-parser nemotron_v3 
      --tool-call-parser qwen3_coder
      --mamba-ssm-cache-dtype float32
      --trust-remote-code
      --enable-auto-tool-choice
      --enable-prefix-caching
      --attention-backend flashinfer
      --kv-cache-dtype fp8
      --compilation-config '{"cache_dir": "/root/.cache/vllm"}'
    restart: "no"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 30s
      timeout: 10s
      retries: 10
    depends_on:
      vllm-embed: 
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  vllm-gemma4:
    #image: vllm/vllm-openai:latest
    build:
      context: .
      dockerfile: Dockerfile.vllm
    container_name: vllm-gemma4
    network_mode: host
    ipc: host
    #ports:
    #  - "8090:8000" # VLLM API access
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
      - ${HOME}/gb10/vllm_cache/vllm_gemma4:/root/.cache/vllm
    #environment:
    #  - VLLM_NVFP4_GEMM_BACKEND=marlin
    command: >
      google/gemma-4-26B-A4B-it
      --tensor-parallel-size 1
      --port 8090
      --max-model-len 256144
      --gpu-memory-utilization 0.60
      --trust-remote-code
      --enable-prefix-caching
      --kv-cache-dtype fp8
      --reasoning-parser gemma4
      --tool-call-parser gemma4
      --enable-auto-tool-choice
      --enable-chunked-prefill
      --max-num-batched-tokens 32768
      --compilation-config '{"cache_dir": "/root/.cache/vllm"}'
    restart: "no"
    depends_on:
      vllm-embed: 
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 30s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]