global:
  scrape_interval: 10s

scrape_configs:
- job_name: vmagent
  static_configs:
  - targets:
    - vmagent:8429
- job_name: victoriametrics
  static_configs:
  - targets:
    - victoriametrics:8428
- job_name: 'redfish-discovery'
  http_sd_configs:
    - url: 'http://redfishagent:8000/api/inventory/targets'

  relabel_configs:
    # 1. Extract the 'target' value from the full URL string
    # This looks at: http://idrac-exporter:9348/metrics?target=redfish-mockup-14g
    # and captures: redfish-mockup-14g
    - source_labels: [__address__]
      regex: '.*target=([^&]+).*'
      target_label: instance

    # 2. Clean up the __address__ label
    # Prometheus needs the __address__ to be JUST 'host:port' to connect properly.
    # This strips the 'http://' and the '/metrics?target=...' parts.
    #- source_labels: [__address__]
    #  regex: '(?:https?://)?([^/]+).*'
    #  target_label: __address__